import { useEffect, useState } from 'react';
import { Crown, Star, Trophy } from 'lucide-react';
import UserAvatar from './UserAvatar';
import type { MonthlyStar, PublicLeaderboardRow } from '../domain/internalEconomyTypes.ts';
import { loadMonthlyStar, loadPublicLeaderboard } from '../services/phaseThreeEconomyService.ts';

export default function PublicRecognition(){
  const [leaders,setLeaders]=useState<PublicLeaderboardRow[]>([]);const [star,setStar]=useState<MonthlyStar|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState(false);
  useEffect(()=>{void(async()=>{const [l,s]=await Promise.all([loadPublicLeaderboard(),loadMonthlyStar()]);setLoading(false);if(!l.ok||!s.ok){console.error('public recognition failed',!l.ok?l.error:s.ok?null:s.error);setError(true);return;}setLeaders(l.data);setStar(s.data);})();},[]);
  return <section className="container-app py-14" dir="rtl"><div className="mb-8 text-center"><span className="text-sm font-bold text-gold-600">التميز والتحفيز</span><h2 className="mt-2 text-3xl font-extrabold text-navy-900">لوحة الشرف</h2></div>{loading?<p className="text-center text-gray-500">جارٍ تحميل لوحة الشرف...</p>:error?<p className="text-center text-rose-600">تعذر تحميل لوحة الشرف حالياً.</p>:<div className="grid gap-6 lg:grid-cols-3"><div className="card p-6 lg:col-span-2"><h3 className="mb-4 flex items-center gap-2 font-extrabold text-navy-900"><Trophy className="h-5 w-5 text-gold-500"/>أفضل 10 أعضاء</h3>{leaders.length===0?<p className="text-sm text-gray-500">ستظهر النتائج بعد تسجيل حركات النقاط.</p>:<div className="grid gap-3 sm:grid-cols-2">{leaders.map(row=><div key={row.studentId} className="flex items-center gap-3 rounded-xl bg-gray-50 p-3"><span className="w-6 text-center font-extrabold text-gold-600">{row.rank}</span><UserAvatar name={row.studentName} avatarPath={row.avatarPath} className="h-10 w-10"/><div className="min-w-0"><p className="truncate font-bold text-navy-900">{row.studentName}</p><p className="text-xs text-gray-500">{row.totalPoints} نقطة</p></div></div>)}</div>}</div><div className="card relative overflow-hidden bg-gradient-to-br from-gold-50 to-amber-100 p-6 text-center"><Crown className="mx-auto h-9 w-9 text-gold-600"/><h3 className="mt-2 font-extrabold text-navy-900">نجم الشهر</h3>{star?<><UserAvatar name={star.studentName} avatarPath={star.avatarPath} className="mx-auto mt-5 h-20 w-20" fallbackClassName="bg-gold-500 text-2xl text-white"/><p className="mt-3 text-lg font-extrabold text-navy-900">{star.studentName}</p><p className="text-sm font-bold text-gold-700"><Star className="ml-1 inline h-4 w-4"/>{star.pointsLast30Days} نقطة خلال 30 يوماً</p></>:<p className="mt-8 text-sm text-gray-600">لا يوجد نجم شهر بعد؛ يظهر عند وجود رصيد موجب خلال آخر 30 يوماً.</p>}</div></div>}</section>;
}
