-- Forward-only fix for manual-path metadata generated by own-committee
-- localization RPCs. The existing helper walks JSON objects but returns no
-- leaves for arrays, so translated scalar-array values such as
-- responsibilities.0 are persisted without their exact manual path.

BEGIN;

CREATE OR REPLACE FUNCTION private.localization_leaf_paths(
  p_object jsonb,
  p_prefix text
)
RETURNS text[]
LANGUAGE plpgsql
IMMUTABLE
SECURITY DEFINER
SET search_path = ''
AS $function$
DECLARE
  v_paths text[] := '{}'::text[];
  v_key text;
  v_value jsonb;
  v_child text[];
  v_path text;
  v_ordinality bigint;
BEGIN
  IF p_object IS NULL THEN
    RETURN v_paths;
  END IF;

  IF jsonb_typeof(p_object) = 'string' THEN
    IF p_prefix <> '' THEN
      v_paths := array_append(v_paths, p_prefix);
    END IF;
    RETURN v_paths;
  END IF;

  IF jsonb_typeof(p_object) = 'object' THEN
    FOR v_key, v_value IN SELECT key, value FROM jsonb_each(p_object) LOOP
      v_path := CASE WHEN p_prefix = '' THEN v_key ELSE p_prefix || '.' || v_key END;
      v_child := private.localization_leaf_paths(v_value, v_path);
      v_paths := v_paths || v_child;
    END LOOP;
    RETURN v_paths;
  END IF;

  IF jsonb_typeof(p_object) = 'array' THEN
    FOR v_value, v_ordinality IN
      SELECT value, ordinality
      FROM jsonb_array_elements(p_object) WITH ORDINALITY
    LOOP
      v_path := CASE
        WHEN p_prefix = '' THEN (v_ordinality - 1)::text
        ELSE p_prefix || '.' || (v_ordinality - 1)::text
      END;
      v_child := private.localization_leaf_paths(v_value, v_path);
      v_paths := v_paths || v_child;
    END LOOP;
  END IF;

  RETURN v_paths;
END
$function$;

COMMIT;
